#
#  Copyright (c) 2017, Nest Labs, Inc.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

SRC = draft-rquattle-spinel-core.md.in
EDITOR_NAME_HACK = James Woodyatt

include ../mmark.make

.INTERMEDIATE: draft-rquattle-spinel-core.md

draft-rquattle-spinel-core.xml: \
	draft-rquattle-spinel-core.md \
	appendix-comparison.md \
	appendix-examples.md \
	appendix-framing.md \
	appendix-test-vectors.md \
	detail-capabilities.md \
	detail-commands.md \
	detail-properties-core.md \
	detail-properties-debug.md \
	detail-properties-ipv6.md \
	detail-properties-net.md \
	detail-properties-phy.md \
	detail-properties.md \
	detail-status.md \
	iana-considerations.md \
	intro.md \
	intro-encoding.md \
	intro-frames.md \
	intro-properties.md \
	security-considerations.md \
	terminology.md \
	$(NULL)
